/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package giffgaff

import giffgaff.model.ProductList
import giffgaff.model.ProductResult

class App {

    static void main(String[] args) {
        FileReader fileReader = new FileReader("product_list.json")
        ProductList productList = new ProductListParser().parse(fileReader.content)
        ProductSearcher productSearcher = new ProductSearcher(productList)
        boolean promptUser = true

        print("What is the product name?");
        while(promptUser) {
            Scanner scanner = new Scanner(System.in)
            String searchTerm = scanner.nextLine()
            ProductResult productResult = productSearcher.search(searchTerm)
            if(productResult.found) {
                println("Name: ${productResult.product.name}")
                println("Price: ${productResult.product.price}")
                println("Quantity: ${productResult.product.quantity}")
                promptUser = false
            }
            else {
                println("Sorry, that product was not found in our inventory.")
                print("What is the product name?");
            }
        }
    }
}
