[package]
name = "json_serdes_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.24", features = ["blocking", "gzip", "json"] }
serde_json = { version = "1.0.113" }
