[package]
name = "bakery-tutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "1.1.0-rc.1", features = [ "sqlx-mysql", "runtime-async-std-native-tls", "macros" ] }
futures = "0.3.30"
