[package]
name = "learn-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
num = { version = "0.4.1", features = [] }
serde = "1.0.196"
uuid = { version = "1.7.0" }
