/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.master

import com.master.model.Person

class App {
    String getGreeting() {
        return 'Hello World!'
    }

    static void main(String[] args) {
        Person person = new Person(name: 'Thando',last: "Mafela")

        println(person.getNameAndLast())
        println new App().greeting

        name()
    }

    def static name() {
        return {
            println "Thando"
        }.call()
    }
}
