version: '2'
services:
  vertx-musicstore:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
      - "mongo"
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=music
      - POSTGRES_PASSWORD=music
      - POSTGRES_DB=musicdb
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"