[package]
name = "qdrant-app"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
qdrant-client = "1.9.0"
serde_json = "1.0.117"
tokio = { version = "1.38.0", features = ["rt-multi-thread"] }
tonic = "0.11.0"
serde = { version = "1.0.203", features = ["derive"] }
