name: vertx_event_bus
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  js: ^0.6.3
  logging: ^1.0.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  quiver: ^3.1.0
#  json_object: ^1.0.19
