micronaut:
  application:
    name: demo
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/micronaut
    driverClassName: org.postgresql.Driver
    username: postgres
    password: secret
    schema-generate: CREATE_DROP
    dialect: POSTGRES
---
omdb:
  base-url: http://www.omdbapi.com/
  # Create your own apikey here http://www.omdbapi.com/. It's free
  apikey: xxxxxxxxxxxx
